project/enroll/urls.py
from django.urls import path
from .import views 

app_name = 'enroll'
urlpatterns = [
    
    path('add_and_show_data/',views.add_show,name='add_and_show_data'),
     path('update_data/<int:id>/',views.update_data,name='update_data'),
    path('delete_student/<int:id>/',views.delete_data,name='delete_student'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enroll/',include('enroll.urls',namespace='enroll'))
]

project/enroll/models.py
from django.db import models

class User(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)

project/enroll/forms.py
from django import forms 
from .models import User
from django.core import validators

class studentRegistration(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name','email','password']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class':'form-control'}),
            'password': forms.PasswordInput(render_value=True,attrs={'class':'form-control'}),
        }

project/enroll/views.py
from django.shortcuts import render,redirect
from .forms import studentRegistration
from .models import User

# The Function Will Add New Student And Show All Student 
def add_show(request):
    form = studentRegistration()
    if request.method == 'POST':
        form = studentRegistration(request.POST)
        if form.is_valid():
            form.save()
        else:
            form = studentRegistration()   
    student = User.objects.all()         
    return render(request,'enroll/add_and_show_data.html',{'form':form,'student':student})

# The Function Will Update Student
def update_data(request,id):
        user = User.objects.get(id=id) 
        form = studentRegistration(instance=user)
        if request.method == 'POST':
            form = studentRegistration(request.POST,instance=user)
            if form.is_valid():
                form.save()
            else:
                 user = User.objects.get(id=id) 
                 form = studentRegistration(instance=user) 
        return render(request,'enroll/update_data.html',{'form':form})           

# The Function Will Delete Student 
def delete_data(request,id):
    user = User.objects.get(id=id) 
    user.delete()
    return redirect('enroll:add_and_show_data')

project/enroll/templates/enroll/add_and_show_data.html
{% extends 'enroll/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-sm-4">
            <h4 class="text-center alert alert-info"> Add New Student </h4>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" class="btn btn-success" value="Add">
            </form>
        </div>
    <div class="col-sm-8">
        <h4 class="text-center alert alert-info"> Show Student Information </h4>
        
        {% if student %}
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nmae</th>
                    <th scope="col">E-Mail</th>
                    <th scope="col">Password</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                 {% for stu in student %}   
                <tr>
                    <th scope="row">{{stu.id}}</th>
                    <td>{{stu.name}}</td>
                    <td>{{stu.email}}</td>
                    <td>{{stu.password}}</td>
                    <td>
                        <a href="{% url 'enroll:update_data' stu.id %}" class="btn btn-warning btn-sm"> Edit </a>
                        <a href="{% url 'enroll:delete_student' stu.id %}" class="btn btn-danger btn-sm"> Delete </a>
                    </td>
                </tr>
               {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h4 class="text-center alert alert-danger"> No Records </h4>    
        {% endif %}
            
    </div>    
    </div>
{% endblock %}   

project/enroll/templates/enroll/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title> CRUD - Project </title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' href='{% static "enroll/css/bootstrap.css" %}'>
  
</head>
<body>
    <div class="container mt-5">
        <h2 class="text-center alert alert-danger"> Function Based View ModelForm CRUD Project </h2>
        {% block content %}
        {% endblock %}    
    </div>
    <script src='{% static "enroll/js/bootstrap.js" %}'></script>    
    <script src='{% static "enroll/js/jquery.js" %}'></script> 
    <script src='{% static "enroll/js/popper.js" %}'></script> 
</body>
</html>

project/enroll/templates/enroll/update_data.html
{% extends 'enroll/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-sm-8 offset-2">
            <h4 class="alert alert-info text-center"> Update Student Information </h4>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit"  class="btn btn-success" value="Update">
                <a  class="btn btn-primary" href="{% url 'enroll:add_and_show_data'%}"> Back To Home </a>
            </form>
        </div>
    </div>
{% endblock %}   